window.onload = function () {
	img_fix();
	nav_menu_left();
	button_out_left();
	button_out_right();
	submit();
	title_right_single();
	title_left_single();
	date1_left_single();
	date1_right_single();
	postwords_left_single();
	postwords_right_single();
	datei_left_single();
	datei_bottom_single();
	if(sidebar_fix_bool){
		sidebar_fix();
	}
	sidebar_fix_h2();
	col3_sidebar_action();
};