window.onload = function () {
	img_fix();
	//light();
	//sidebar_light();
	nav_menu_left();
	button_out_left();
	button_out_right();
	//comment_left();
	//comment_right();
	//comment_bottom();
	//postwords_left();
	//postwords_bottom();
	//title_right();
	//title_left();
	//date1_right();
	//date1_left();
	logo_right();
	logo_left();
	left_top();
	//postwords_top();
	//date_right();
	//date_left();
	submit();
	title_right_single();
	title_left_single();
	date1_left_single();
	date1_right_single();
	postwords_left_single();
	postwords_right_single();
	datei_left_single();
	datei_bottom_single();
	if(sidebar_fix_bool){
		sidebar_fix();
	}
	sidebar_fix_h2();
};